apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homesite
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/daveasam141/argocd-config-demo.git
    targetRevision: argocdbranch
    path: homesite
  destination: 
    server: https://kubernetes.default.svc
    namespace: homesite
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true