apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: confluence
  labels:
    app: postgres
data:
  POSTGRES_DB: confluence
  POSTGRES_USER: confluence
  POSTGRES_PASSWORD: SecurePassword