apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: postgres-volume-claim
#   namespace: confluence  
#   labels:
#     app: postgres
# spec:
#   storageClassName: gp3
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 10Gi